name: weather
description: Weather App Test Project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.3
  logger: ^2.0.2+1
  get_it: ^7.6.4
  dio: ^5.0.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_dotenv: ^5.0.2
  retrofit: ^4.0.1
  permission_handler: ^11.0.1
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  flutter_svg: ^2.0.9
  charts_flutter_new: ^0.12.0
  geolocator: ^9.0.2
  shimmer: ^3.0.0
  geocoding: ^2.2.0
  open_street_map_search_and_pick: ^0.1.0
  latlong2: ^0.8.2

dependency_overrides: 
   intl: ^0.18.0
   permission_handler: ^11.0.1
  

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0
  auto_route_generator:
  build_runner: 2.4.8
  flutter_gen_runner: ^5.3.1
  retrofit_generator: 
  freezed: ^2.3.2
  json_serializable: ^6.4.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/svgs/

  fonts:
    - family: CapsuleSansText
      fonts:
        - asset: assets/fonts/CapsuleSansText/CapsuleSansText-Bold.ttf
          weight: 700
        - asset: assets/fonts/CapsuleSansText/CapsuleSansText-Book.ttf
          weight: 600
        - asset: assets/fonts/CapsuleSansText/CapsuleSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/CapsuleSansText/CapsuleSansText-Light.ttf
          weight: 400

flutter_launcher_icons:
  android: "ic_my_new_icon"
  adaptive_icon_background: "#00000"
  ios: "AppIcon"
  image_path: "assets/images/launcher.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - assets/env/*
      - config/
    outputs:
      class_name: AppAssets